name: Refresh Contest Data

on:
  schedule:
    - cron: "30 19 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Refresh contest data
        run: bun run refresh-contest-data

      - name: Commit updated contest data
        run: |
          git config --global user.email "bot@therealsuji.tk"
          git config --global user.name "thefakesujitk"
          git add --all
          git commit -m "chore: refresh latest contest data" || true
          git push